# Generated by Django 3.2.18 on 2023-04-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0017_auto_20180317_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['name'], 'permissions': (('see_all_programmes', 'Can see all programmes'),), 'verbose_name': 'programme', 'verbose_name_plural': 'programmes'},
        ),
    ]
