# Generated by Django 2.2.28 on 2023-01-30 19:15

from django.db import migrations
import radioco.schedules.wrapper


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20180317_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='recurrences',
            field=radioco.schedules.wrapper.RecurrenceFieldWrapper(verbose_name='recurrences'),
        ),
    ]
