# Generated by Django 3.2.18 on 2023-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20230130_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='runtime',
            field=models.DurationField(help_text='runtime in (dd) hh:mm:ss', verbose_name='runtime'),
        ),
    ]
